### ISSUE TITLE
Acortar url's con IP

### ISSUE THREAD

**Issue by jonayrb** [damianpumar/Curtme#16]
Buenas, he detectado que si intentas acortar una url que contenga una IP en el parámetro **sourceURL** la petición tarda en responder más de 20 segundos, cuando lo habitual que no pase de unos 2-3 segundos aproximadamente. Por ejemplo:
_endpoint: _https://curtme.org/_
request: 
_{
  "sourceURL": "http://192.168.0.1:3100/test/d0RSQnlXa1lSZHJNUmdNRkUwSmUzVGxKckVIUS9iM0RuVWlyekd6QkhnRT0="
}_
response time: 21.62 segundos_

Un saludo

**Comment by damianpumar** [comment]
Buenas Jonay, voy a revisar porque tarda tanto tiempo en responder, de todas maneras, esa es una IP privada, con lo cual para un entorno de test podría llegar a tener sentido, pero para un la versión productiva no, ya que no tiene sentido redireccionar a una IP privada.

Saludos.
