### ISSUE TITLE
Permitir llamadas con localhost en sourceURL

### ISSUE THREAD

**Issue by jonayrb** [damianpumar/Curtme#17]
Buenas, he detectado que si intentas acortar una url que contenga localhost en el parámetro **sourceURL** la petición responde con un BadRequest. Por ejemplo:
__endpoint: _https://curtme.org/_
request: 
_{
  "sourceURL": "http://localhost/test/d0RSQnlXa1lSZHJNUmdNRkUwSmUzVGxKckVIUS9iM0RuVWlyekd6QkhnRT0="
}__

Supongo que será un comportamiento deseado, pero para pruebas  y tests en local, estaría genial que retornara un 200.

Muchas gracias

**Comment by damianpumar** [comment]
Buenas Jonay, probablemente puede ser una buena opción montar un server de test para este caso.
Te animarías a hacer un fork del proyecto e implementar este cambio para un entorno de test?
Me gustaría escuchar alguna propuesta técnica que creas necesaria y viable para este tipo de comportamiento.

Gracias por el tiempo de reportar este issue!
